FROM node:20

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build TypeScript (if you're using TS)
RUN npm run build

# Expose port
EXPOSE 5001

# Production start command
CMD ["npm", "start"]